<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>snappy_launch</name>
  <version>0.1.0</version>
  <description>Whole-vehicle launch and deployment configuration for the Snappy AUV.</description>
  <maintainer email="kraken@todo.todo">AUVic</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>micro_ros_agent</exec_depend>
  <exec_depend>snappy_autonomy</exec_depend>
  <exec_depend>snappy_computer_vision</exec_depend>
  <exec_depend>snappy_control</exec_depend>
  <exec_depend>snappy_drivers</exec_depend>
  <exec_depend>snappy_estimation</exec_depend>
  <exec_depend>waterlinked_dvl_driver</exec_depend>
  <exec_depend>xsens_mti_ros2_driver</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
